
set STARTUP_HOOKS_PROJECT_PATH=%1
set REL_ENTRYPOINT_ASSEMBLY_PATH=%2
set IMAGE_NAME=%3

docker build --build-arg ARG_ENTRYPOINT_ASSEMBLY="%REL_ENTRYPOINT_ASSEMBLY_PATH%" -t "%IMAGE_NAME%" "%STARTUP_HOOKS_PROJECT_PATH%"
