set DEBUGGER_DOCKERFILE=%1
set STARTUP_HOOKS_PROJECT_PATH=%2
set DEBUGGER_BASE_IMAGE=%3
set STARTUP_HOOKS_BUILD_IMAGE=%4
set IMAGE_NAME=%5

docker build -f "%DEBUGGER_DOCKERFILE%" ^
    -t "%IMAGE_NAME%" ^
    --build-arg ARG_DEBUGGER_BASE_IMAGE="%DEBUGGER_BASE_IMAGE%" ^
    --build-arg ARG_STARTUP_HOOKS_BUILD_IMAGE="%STARTUP_HOOKS_BUILD_IMAGE%" ^
    "%STARTUP_HOOKS_PROJECT_PATH%"
