
set SOLUTION_PATH=%1
set REL_ASSEMBLY_PATH=%2
set DEBUGGER_IMAGE_NAME=%3
set DEBUGGER_CONTAINER_NAME=%4

docker stop "%DEBUGGER_CONTAINER_NAME%"
docker run --name "%DEBUGGER_CONTAINER_NAME%" -d --rm -v "%SOLUTION_PATH%":/src --entrypoint "dotnet" "%DEBUGGER_IMAGE_NAME%" %REL_ASSEMBLY_PATH%"
